### ISSUE TITLE
Fix Segmentation Fault

### ISSUE THREAD

**Issue by hammesj1** [hammesj1/se420-group-project#1]
Running the program with the supplied test script results in a segmentation fault prior to completion. The cause of the segmentation fault needs to be identified, then resolved.

**Comment by CristianERAU** [comment]
Segmentation fault has been fixed. The problem is that our cout << funtionality for the "I" menu item to select a network was calling an object who's pointer had yet not been assigned. 

Please refer to this link: 2abeb329c298f63a40e48ac3dcd8ff5d832df5ca on line modifications 254 and 256.

**Comment by CristianERAU** [comment]
Issue has been closed and test script is fully functional once more.
